- name: publish-kedro-viz
  uses: kedro-org/publish-kedro-viz@v1

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - main
  workflow_dispatch:
